### ISSUE TITLE
galaxy note 3, transactions hanging on transmitting

### ISSUE THREAD

**Issue by DrBlackross** [Stouse49/goldcoin-wallet#1]
worked after the beta 3 email you sent me, then with the newest update just won't send any coins to the exchange (same as before).... so i've shifted over to a paper wallet for the time being.

i've flushed the blockchain, added nodes from goldcoins website and flushed the blockchain.... etc (with every combination it still won't send a transaction)

**Comment by Stouse49** [comment]
Use the Report issue function under Settings | Diagnostics and we can look at the logs and find a solution.

**Comment by Stouse49** [comment]
Closing this due to no further feedback.
